services:
  postgres:
    image: postgres:16-alpine
    container_name: digit-pos-postgres
    restart: unless-stopped

    env_file:
      - ./.env.postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurant_pos"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: backend
    restart: unless-stopped

    ports:
      - "127.0.0.1:5500:5500"

    env_file:
      - ./server/.env

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: frontend
    restart: unless-stopped

    ports:
      - "127.0.0.1:3005:80"

    depends_on:
      - backend

volumes:
  postgres_data:
