services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "5500:5500"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    depends_on:
      - backend