export const ROLES = {
  // New role model
  SUPER_ADMIN: 'SUPER_ADMIN',
  RESTAURANT_OWNER: 'RESTAURANT_OWNER',
  MANAGER: 'MANAGER',
  CASHIER: 'CASHIER',
  WAITER: 'WAITER',
  CHEF: 'CHEF',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  ACCOUNTANT: 'ACCOUNTANT',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  // Legacy role values kept for backward compatibility
  ADMIN: 'ADMIN',
  KITCHEN: 'KITCHEN',
  CUSTOMER: 'CUSTOMER'
};

export const PERMISSIONS = {
  PLATFORM_MANAGE: 'platform.manage',
  TENANTS_MANAGE: 'tenants.manage',
  PLANS_MANAGE: 'plans.manage',
  SUBSCRIPTIONS_MANAGE: 'subscriptions.manage',
  FEATURES_MANAGE: 'features.manage',
  GLOBAL_REPORTS_VIEW: 'global_reports.view',
  AUDIT_LOGS_VIEW: 'audit_logs.view',
  SUPPORT_IMPERSONATE: 'support.impersonate',

  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_VIEW_LIMITED: 'dashboard.view_limited',
  RESTAURANT_SETTINGS_MANAGE: 'restaurant_settings.manage',
  BRANCHES_MANAGE: 'branches.manage',
  TABLES_VIEW: 'tables.view',
  TABLES_ASSIGN: 'tables.assign',
  TABLES_MANAGE: 'tables.manage',
  STAFF_MANAGE: 'staff.manage',
  ROLES_ASSIGN: 'roles.assign',

  MENU_MANAGE: 'menu.manage',
  MENU_ITEMS_MANAGE: 'menu_items.manage',
  RECIPE_COSTING_MANAGE: 'recipe_costing.manage',

  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_MANAGE: 'inventory.manage',
  INVENTORY_ADJUST_MANAGE: 'inventory_adjust.manage',
  STOCK_IN_CREATE: 'stock_in.create',
  STOCK_OUT_CREATE: 'stock_out.create',
  WASTAGE_TRACK: 'wastage.track',
  SUPPLIERS_MANAGE: 'suppliers.manage',

  ORDERS_VIEW: 'orders.view',
  ORDERS_MANAGE: 'orders.manage',
  ORDERS_CREATE: 'orders.create',
  ORDERS_UPDATE: 'orders.update',
  ORDERS_SEND_TO_KITCHEN: 'orders.send_to_kitchen',
  KITCHEN_ORDERS_MANAGE: 'kitchen_orders.manage',
  KITCHEN_ORDERS_MONITOR: 'kitchen_orders.monitor',
  KITCHEN_ORDERS_VIEW: 'kitchen_orders.view',
  KITCHEN_ORDERS_UPDATE_STATUS: 'kitchen_orders.update_status',
  KITCHEN_QUEUE_MANAGE: 'kitchen_queue.manage',
  FOOD_PREPARATION_MANAGE: 'food_preparation.manage',
  KITCHEN_ORDER_STATUS_VIEW: 'kitchen_order_status.view',

  BILLING_MANAGE: 'billing.manage',
  PAYMENTS_PROCESS: 'payments.process',
  SPLIT_BILL_USE: 'split_bill.use',
  DISCOUNTS_APPROVE: 'discounts.approve',
  DISCOUNTS_APPROVE_LIMITED: 'discounts.approve_limited',
  DISCOUNTS_APPLY_LIMITED: 'discounts.apply_limited',
  REFUNDS_PROCESS: 'refunds.process',
  REFUNDS_PROCESS_LIMITED: 'refunds.process_limited',
  RECEIPTS_PRINT: 'receipts.print',

  SALES_REPORTS_VIEW: 'sales_reports.view',
  SALES_REPORTS_VIEW_OWN: 'sales_reports.view_own',
  PROFIT_REPORTS_VIEW: 'profit_reports.view',
  FINANCIAL_REPORTS_VIEW: 'financial_reports.view',
  TAX_REPORTS_VIEW: 'tax_reports.view',
  EXPORTS_DOWNLOAD: 'exports.download',

  SHIFT_MANAGE: 'shift.manage',
  SHIFT_OPEN: 'shift.open',
  SHIFT_CLOSE_OWN: 'shift.close_own',

  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMER_REQUESTS_MANAGE: 'customer_requests.manage',
  TICKETS_MANAGE: 'tickets.manage',

  DELIVERY_ORDERS_VIEW_ASSIGNED: 'delivery_orders.view_assigned',
  DELIVERY_STATUS_UPDATE: 'delivery_status.update'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.RESTAURANT_OWNER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.RESTAURANT_SETTINGS_MANAGE,
    PERMISSIONS.BRANCHES_MANAGE,
    PERMISSIONS.TABLES_MANAGE,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.ROLES_ASSIGN,
    PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.MENU_ITEMS_MANAGE,
    PERMISSIONS.RECIPE_COSTING_MANAGE,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.INVENTORY_ADJUST_MANAGE,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.KITCHEN_ORDERS_MANAGE,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.SPLIT_BILL_USE,
    PERMISSIONS.DISCOUNTS_APPROVE,
    PERMISSIONS.REFUNDS_PROCESS,
    PERMISSIONS.SALES_REPORTS_VIEW,
    PERMISSIONS.PROFIT_REPORTS_VIEW,
    PERMISSIONS.AUDIT_LOGS_VIEW,
    PERMISSIONS.SHIFT_MANAGE
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.TABLES_MANAGE,
    PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.MENU_ITEMS_MANAGE,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.KITCHEN_ORDERS_MONITOR,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.SPLIT_BILL_USE,
    PERMISSIONS.DISCOUNTS_APPROVE_LIMITED,
    PERMISSIONS.REFUNDS_PROCESS_LIMITED,
    PERMISSIONS.SALES_REPORTS_VIEW,
    PERMISSIONS.SHIFT_MANAGE
  ],
  [ROLES.CASHIER]: [
    PERMISSIONS.DASHBOARD_VIEW_LIMITED,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.PAYMENTS_PROCESS,
    PERMISSIONS.SPLIT_BILL_USE,
    PERMISSIONS.DISCOUNTS_APPLY_LIMITED,
    PERMISSIONS.RECEIPTS_PRINT,
    PERMISSIONS.SHIFT_OPEN,
    PERMISSIONS.SHIFT_CLOSE_OWN,
    PERMISSIONS.SALES_REPORTS_VIEW_OWN
  ],
  [ROLES.WAITER]: [
    PERMISSIONS.TABLES_VIEW,
    PERMISSIONS.TABLES_ASSIGN,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_SEND_TO_KITCHEN,
    PERMISSIONS.KITCHEN_ORDER_STATUS_VIEW,
    PERMISSIONS.CUSTOMER_REQUESTS_MANAGE
  ],
  [ROLES.CHEF]: [
    PERMISSIONS.KITCHEN_ORDERS_VIEW,
    PERMISSIONS.KITCHEN_ORDERS_UPDATE_STATUS,
    PERMISSIONS.KITCHEN_QUEUE_MANAGE,
    PERMISSIONS.FOOD_PREPARATION_MANAGE
  ],
  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.INVENTORY_ADJUST_MANAGE,
    PERMISSIONS.STOCK_IN_CREATE,
    PERMISSIONS.STOCK_OUT_CREATE,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.RECIPE_COSTING_MANAGE,
    PERMISSIONS.WASTAGE_TRACK
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.FINANCIAL_REPORTS_VIEW,
    PERMISSIONS.SALES_REPORTS_VIEW,
    PERMISSIONS.TAX_REPORTS_VIEW,
    PERMISSIONS.EXPORTS_DOWNLOAD
  ],
  [ROLES.DELIVERY_PARTNER]: [
    PERMISSIONS.DELIVERY_ORDERS_VIEW_ASSIGNED,
    PERMISSIONS.DELIVERY_STATUS_UPDATE
  ],
  [ROLES.CUSTOMER_SUPPORT]: [
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.TICKETS_MANAGE
  ]
};

export const TABLE_STATUSES = ['AVAILABLE', 'OCCUPIED', 'RESERVED', 'CLEANING'];

export const ORDER_TYPES = ['DINE_IN', 'TAKEAWAY', 'DELIVERY'];
export const ORDER_STATUSES = ['PENDING', 'PREPARING', 'READY', 'SERVED', 'COMPLETED', 'CANCELLED'];
export const ACTIVE_ORDER_STATUSES = ['PENDING', 'PREPARING', 'READY', 'SERVED'];
export const BILLABLE_ORDER_STATUSES = ['READY', 'SERVED'];

export const PAYMENT_METHODS = ['CASH', 'CARD', 'QR', 'ONLINE', 'SPLIT'];
export const PAYMENT_STATUSES = ['PAID', 'UNPAID', 'PARTIAL'];

export const LOW_STOCK_THRESHOLD_DEFAULT = 10;
